runtime: python39

entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
  # Variáveis de ambiente que você precisar adicionar
  EXAMPLE_VARIABLE: 'example_value'

handlers:
  - url: /static
    static_dir: static  # Diretório onde seus arquivos estáticos estão armazenados

  - url: /.*
    script: auto
