runtime: python310  # Ou outra versão do Python, se necessário

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app

env_variables:
  # Variáveis de ambiente, caso você precise de alguma
  EXAMPLE_VAR: "value"

instance_class: F2  # Ou outra classe de instância, dependendo das necessidades da aplicação

automatic_scaling:
  min_instances: 1
  max_instances: 10
